`Link dos dados para download`  

https://www.kaggle.com/datasets/rehanliaqat17/mashrooms-classifications

In [1]:
import pandas as pd

In [2]:
df_cogumelos = pd.read_csv('./data/mushrooms.csv')

df_cogumelos.head(10)

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
5,e,x,y,y,t,a,f,c,b,n,...,s,w,w,p,w,o,p,k,n,g
6,e,b,s,w,t,a,f,c,b,g,...,s,w,w,p,w,o,p,k,n,m
7,e,b,y,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,s,m
8,p,x,y,w,t,p,f,c,n,p,...,s,w,w,p,w,o,p,k,v,g
9,e,b,s,y,t,a,f,c,b,g,...,s,w,w,p,w,o,p,k,s,m

In [3]:
df_cogumelos.info()

<class 'pandas.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   str
 1   cap-shape                 8124 non-null   str
 2   cap-surface               8124 non-null   str
 3   cap-color                 8124 non-null   str
 4   bruises                   8124 non-null   str
 5   odor                      8124 non-null   str
 6   gill-attachment           8124 non-null   str
 7   gill-spacing              8124 non-null   str
 8   gill-size                 8124 non-null   str
 9   gill-color                8124 non-null   str
 10  stalk-shape               8124 non-null   str
 11  stalk-root                8124 non-null   str
 12  stalk-surface-above-ring  8124 non-null   str
 13  stalk-surface-below-ring  8124 non-null   str
 14  stalk-color-above-ring    8124 non-null   str
 15  stalk-color-below-ring    8124 non-null   str
 16  veil-type                 8124 non-null   str
 17  veil-color                8124 non-null   str
 18  ring-number               8124 non-null   str
 19  ring-type                 8124 non-null   str
 20  spore-print-color         8124 non-null   str
 21  population                8124 non-null   str
 22  habitat                   8124 non-null   str
dtypes: str(23)
memory usage: 1.4 MB

In [4]:
for colunas in df_cogumelos.columns:
    print(f'Coluna: {colunas} | Valores possíveis: {df_cogumelos[colunas].unique()}')

Coluna: class | Valores possíveis: <StringArray>
['p', 'e']
Length: 2, dtype: str
Coluna: cap-shape | Valores possíveis: <StringArray>
['x', 'b', 's', 'f', 'k', 'c']
Length: 6, dtype: str
Coluna: cap-surface | Valores possíveis: <StringArray>
['s', 'y', 'f', 'g']
Length: 4, dtype: str
Coluna: cap-color | Valores possíveis: <StringArray>
['n', 'y', 'w', 'g', 'e', 'p', 'b', 'u', 'c', 'r']
Length: 10, dtype: str
Coluna: bruises | Valores possíveis: <StringArray>
['t', 'f']
Length: 2, dtype: str
Coluna: odor | Valores possíveis: <StringArray>
['p', 'a', 'l', 'n', 'f', 'c', 'y', 's', 'm']
Length: 9, dtype: str
Coluna: gill-attachment | Valores possíveis: <StringArray>
['f', 'a']
Length: 2, dtype: str
Coluna: gill-spacing | Valores possíveis: <StringArray>
['c', 'w']
Length: 2, dtype: str
Coluna: gill-size | Valores possíveis: <StringArray>
['n', 'b']
Length: 2, dtype: str
Coluna: gill-color | Valores possíveis: <StringArray>
['k', 'n', 'g', 'p', 'w', 'h', 'u', 'e', 'b', 'r', 'y', 'o']
Length: 12, dtype: str
Coluna: stalk-shape | Valores possíveis: <StringArray>
['e', 't']
Length: 2, dtype: str
Coluna: stalk-root | Valores possíveis: <StringArray>
['e', 'c', 'b', 'r', '?']
Length: 5, dtype: str
Coluna: stalk-surface-above-ring | Valores possíveis: <StringArray>
['s', 'f', 'k', 'y']
Length: 4, dtype: str
Coluna: stalk-surface-below-ring | Valores possíveis: <StringArray>
['s', 'f', 'y', 'k']
Length: 4, dtype: str
Coluna: stalk-color-above-ring | Valores possíveis: <StringArray>
['w', 'g', 'p', 'n', 'b', 'e', 'o', 'c', 'y']
Length: 9, dtype: str
Coluna: stalk-color-below-ring | Valores possíveis: <StringArray>
['w', 'p', 'g', 'b', 'n', 'e', 'y', 'o', 'c']
Length: 9, dtype: str
Coluna: veil-type | Valores possíveis: <StringArray>
['p']
Length: 1, dtype: str
Coluna: veil-color | Valores possíveis: <StringArray>
['w', 'n', 'o', 'y']
Length: 4, dtype: str
Coluna: ring-number | Valores possíveis: <StringArray>
['o', 't', 'n']
Length: 3, dtype: str
Coluna: ring-type | Valores possíveis: <StringArray>
['p', 'e', 'l', 'f', 'n']
Length: 5, dtype: str
Coluna: spore-print-color | Valores possíveis: <StringArray>
['k', 'n', 'u', 'h', 'w', 'r', 'o', 'y', 'b']
Length: 9, dtype: str
Coluna: population | Valores possíveis: <StringArray>
['s', 'n', 'a', 'v', 'y', 'c']
Length: 6, dtype: str
Coluna: habitat | Valores possíveis: <StringArray>
['u', 'g', 'm', 'd', 'p', 'w', 'l']
Length: 7, dtype: str

In [5]:
df_cogumelos['veil-type'].nunique()

1

In [6]:
# removendo a coluna que tem apenas um único valor único

df_cogumelos.drop(columns='veil-type', inplace=True)

In [7]:
# traduzindo e renomenado o nome das colunas

dicionario_colunas = {
    'class': 'classe',
    'cap-shape': 'forma_chapeu',
    'cap-surface': 'superficie_chapeu',
    'cap-color': 'cor_chapeu',
    'bruises': 'machucados',
    'gill-attachment': 'fixacao_branquia',
    'gill-spacing': 'espacamento_branquia',
    'gill-size': 'tamanho_branquia',
    'gill-color': 'cor_branquia',
    'stalk-shape': 'forma_caule',
    'stalk-root': 'raiz_caule',
    'stalk-surface-above-ring': 'superficie_caule_acima_anel',
    'stalk-surface-below-ring': 'superficie_caule_abaixo_anel',
    'stalk-color-above-ring': 'cor_caule_acima_anel',
    'stalk-color-below-ring': 'cor_caule_abaixo_anel',
    'veil-type': 'tipo_veu',
    'veil-color': 'cor_veu',
    'ring-number': 'numero_anel',
    'ring-type': 'tipo_anel',
    'spore-print-color': 'cor_impresao_esporos',
    'population': 'populacao',
}

df_cogumelos.rename(columns=dicionario_colunas, inplace=True)

In [8]:
print(f'Linhas: {df_cogumelos.shape[0]} | Colunas: {df_cogumelos.shape[1]}')
df_cogumelos.head()

Linhas: 8124 | Colunas: 22

,classe,forma_chapeu,superficie_chapeu,cor_chapeu,machucados,odor,fixacao_branquia,espacamento_branquia,tamanho_branquia,cor_branquia,...,superficie_caule_acima_anel,superficie_caule_abaixo_anel,cor_caule_acima_anel,cor_caule_abaixo_anel,cor_veu,numero_anel,tipo_anel,cor_impresao_esporos,populacao,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,s,w,w,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,s,w,w,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,s,w,w,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,s,w,w,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,s,w,w,w,o,e,n,a,g

In [9]:
df_cogumelos.to_csv('./data/cogumelos_tratados.csv', index=False)